REMOTE_SERVER = "localhost:8080"
REMOTE_SERVER_BASE_URL = "http://" + REMOTE_SERVER
# This should not be here
SECRET_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5MTk1ODg2OCwiaWF0IjoxNjkxOTU4ODY4fQ.mi9ar0R_mHsq1JCvdbEvwHz40fGVgZXIARefYJ9f4iU"  # noqa: S105
HEARTBEAT_INTERVAL_SECONDS = 3
PAYLOAD_DIRECTORY = "payloads"
CLIENT_PORT = 8070
REQUEST_TIMEOUT = 5
